name: 'Clear branch action'
description: 'This action is used to remove the branch when the PR is closed and the branch is merged'

inputs:
  access_token:
    description: 'The access token for the api requests'
    required: true

  excluded_branches:
    description: 'an array passed as string that contains the branches that should never be removed'
    required: false
    default: '[]'

runs:
  using: 'node12'
  main: 'removeBranchOnPR.js'